function init(self)
	msg.post(".", "acquire_input_focus")

	self.collision_id = nil
	self.pressed = false
end

function update(self, dt)
	local pos = go.get_position()
	label.set_text("#cursorLabel", "---- x: " .. pos.x .. "  y: " .. pos.y)
	self.collision_id = nil
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") and self.pressed == true then
		if message.group == hash("location") then
			msg.post("loader:/game_loader#loader", "load_location_from_map")
		end
	end
end

function on_input(self, action_id, action)
	if not action_id or action_id == hash("touch") then
		local action_pos = vmath.vector3(action.x, action.y, 0)
		go.set_position(action_pos)

		-- Revise script control variables; click/touch -- as pressed or released 
		if action.pressed then
			-- When the action reflects a press
			msg.post("#collisionobject", "enable")
			self.pressed = true
			print("Input press detected at ", action_pos)
			
		elseif action.released then
			-- When the action reflects a release
			msg.post("#collisionobject", "disable")
			self.pressed = false
			print("Input release detected at ", action_pos)
		end
	end
end